config/routes.rb
Rails.application.routes.draw do
  resources :vocabularies

  resources :excavations

  resources :artefacts

  devise_for :users
  
  get 'home/index'

  root 'home#index'

end

app/models/excavation.rb
class Excavation < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  
  has_many :artefact_identificators
  has_many :artefacts, through: :artefact_identificators

  belongs_to :creator, class_name: 'User'
  belongs_to :updater, class_name: 'User'

  validates :name, presence: true, unless: :dai_gazetter_id?
  validates :dai_gazetter_id, presence: true, unless: :name?


  def name
  	read_attribute(:name).present? ? read_attribute(:name) : dai_gazetter_id
  end
end

app/controllers/excavations_controller.rb
class ExcavationsController < ApplicationController
  layout 'page'
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_excavation, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @excavations = Excavation.all
    @hash = Gmaps4rails.build_markers(@excavations) do |excavation, marker|
      marker.lat excavation.latitude
      marker.lng excavation.longitude
      marker.title excavation.name
      marker.infowindow "<a href='#{url_for(excavation)}'>#{excavation.name}</a>"
    end
    respond_with(@excavations)
  end

  def show
    @hash = Gmaps4rails.build_markers(@excavation) do |excavation, marker|
      marker.lat excavation.latitude
      marker.lng excavation.longitude
      marker.title excavation.name
    end
    respond_with(@excavation)
  end

  def new
    @excavation = Excavation.new
    respond_with(@excavation)
  end

  def edit
  end

  def create
    @excavation = Excavation.new(excavation_params.merge(creator: current_user, updater: current_user))
    flash[:notice] = 'Excavation was successfully created.' if @excavation.save
    respond_with(@excavation)
  end

  def update
    flash[:notice] = 'Excavation was successfully updated.' if @excavation.update(excavation_params.merge(updater: current_user))
    respond_with(@excavation)
  end

  def destroy
    @excavation.destroy
    respond_with(@excavation)
  end

  private
    def set_excavation
      @excavation = Excavation.find(params[:id])
    end

    def excavation_params
      params.require(:excavation).permit(:name, :dai_gazetter_id, :shortcut, :creator, :updater, :address, :latitude, :longitude)
    end
end

app/helpers/excavations_helper.rb
module ExcavationsHelper
end

app/views/excavations/_form.html.erb
<%= simple_form_for @excavation, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.error_notification %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="general-fields">
        <%= f.input :dai_gazetter_id %>
        <%= f.input :name %>
        <%= f.input :shortcut %>
      </div>
      <%= f.button :submit, class: 'btn btn-primary', style: 'margin-top:20px;' %>
    </div>
    <div class="col-sm-6">
      <div class="well" id="external-data">
        <!-- <%= f.input :address %> -->
        <%= f.input :latitude %>
        <%= f.input :longitude %>
      </div>
    </div>
  </div>
<% end %>

app/views/excavations/edit.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), excavations_path, title: 'back' %> 
    Editing excavation
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Discard changes/back', :back, class: 'btn btn-default' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<%= render 'form' %>

app/views/excavations/index.html.erb
<% content_for :head do %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<% end %>

<% content_for :title_bar do %>
  <h1>
    Excavations
    <%= link_to 'Add excavation', new_excavation_path, class: 'btn btn-default pull-right' if user_signed_in? %>
  </h1>
<% end %>

<h2>
  <i class="fa fa-map-marker" style="color:#428bca;"></i>
  Places
</h2>
<div class="row">
  <div class="col-sm-5">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>DaiGazzetter link</th>
        </tr>
      </thead>
      <tbody>
        <% @excavations.each do |excavation| %>
          <tr>
            <td><%= link_to excavation.name, excavation %> <%= "(#{excavation.shortcut})" if excavation.shortcut.present? %></td>
            <td><%= link_to excavation.dai_gazetter_id, "http://gazetteer.dainst.org/app/#!/show/#{excavation.dai_gazetter_id}", target: :blank %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-7">
    <div style='width: 100%;' class="well">
      <div id="map" style='width: 100%; height: 500px;'></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {mapTypeId: google.maps.MapTypeId.SATELLITE}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/excavations/new.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), excavations_path, title: 'back' %> 
    New excavation
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Discard changes/back', :back, class: 'btn btn-default' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<%= render 'form' %>

app/views/excavations/show.html.erb
<% content_for :head do %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<% end %>

<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), excavations_path, title: 'back' %> <%= @excavation.name %>
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Edit excavation', edit_excavation_path(@excavation), class: 'btn btn-default' %>
      <%= link_to 'Destroy', @excavation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-danger' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<div class="row">
  <div class="col-sm-6">
    <div id="name">
      <p>
        <i class="fa fa-map-marker" style="color:#428bca;"></i>
        <%= @excavation.name %> <%= "(#{@excavation.shortcut})" if @excavation.shortcut.present? %>
      </p>
    </div>
    <%= content_tag "div", id: "gazetter", data: {url: "http://gazetteer.dainst.org/doc/#{@excavation.dai_gazetter_id}.json", place: @excavation.id} do %>
      <div id="loading">Loading details... <%= image_tag('loader.gif') %></div>
      <div id="data" style="display:none;" class="well"></div>
    <% end %>

    <div style='width: 100%;' class="well">
      <div id="map" style='width: 100%; height: 400px;'></div>
      <p><small><strong>Location: </strong><%= "[#{@excavation.latitude}, #{@excavation.longitude}]" %></small></p>
    </div>
    <br>

    <% if user_signed_in? %>
      <p>
        <strong>Creator:</strong>
        <%= @excavation.creator.try(:email) %>
      <br>
        <strong>Updater:</strong>
        <%= @excavation.updater.try(:email) %>
      </p>
    <% end %>

  </div>
  <div class="col-sm-6">
    <h4>Artefacts from <%= @excavation.name %></h4>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>Identificators</td>
          <td>Info</td>
        </tr>
      </thead>
      <tbody>
        <%= render @excavation.artefacts %>
      </tbody>
    </table>
  </div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {mapTypeId: google.maps.MapTypeId.SATELLITE}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15);
  });
</script>


<script type="text/javascript">
jQuery(document).ready(function($) {
  return jQuery.ajax({
    type: "get",
    url: $("#gazetter").data("url"),
    dataType: "json",
    success: function(data) {
      var latitude, links, longitude, names, place;
      $("#loading").hide(data);
      $("#data").show(data);
      $("#data").append("<p><strong>Name: </strong>" + data.prefName.title + "</p>");
      names = "<strong>Other names: </strong>";
      names += "<ul class='list-unstyled'>";
      $.each(data.names, function(i, name) {
        names += "<li>" + name.title + " (" + name.language + ")" + "</li>";
      });
      names += "</ul>";
      $(names).appendTo("#data");
      links = "<strong>Links: </strong>";
      links += "<ul class='list-unstyled'>";
      $.each(data.links, function(i, link) {
        links += "<li>" + "<a href=" + link.object + ">" + link.object + "</a>" + " (" + link.predicate + ")" + "</li>";
      });
      links += "</ul>";
      $(links).appendTo("#data");
      place = $("#gazetter").data("place");
      longitude = data.prefLocation.coordinates[0];
      latitude = data.prefLocation.coordinates[1];
      $("#data").append("<p><strong>Lage: </strong>" + "<em>Breite: </em>" + latitude + ", " + "<em>Länge: </em>" + longitude + "</p>");
      $("#data").append("<p><strong>Liegt in: </strong>" + "<a href=" + data.parent + ">" + data.parent + "</a>" + "</p>");
      $("#data").append("<p><i class='fa fa-info-circle'></i> <strong>Daten von: </strong>" + "<a href=" + data['@id'] + ">" + data['@id'] + "</a>" + "</p>");
    }
  });
});
</script>