config/routes.rb
Rails.application.routes.draw do
  resources :vocabularies

  resources :excavations

  resources :artefacts

  devise_for :users
  
  get 'home/index'

  root 'home#index'

end

app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
  acts_as_tree dependent: :destroy

  has_many :terms, dependent: :destroy
  has_many :specifications, dependent: :destroy
  has_many :artefacts, through: :specifications, source: :specifyable, source_type: "Artefact"
  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :creator, class_name: 'User'
  belongs_to :updater, class_name: 'User'

  accepts_nested_attributes_for :terms, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true

  scope :concept, -> { where(record_type: 'concept') }
  scope :hierarchy, -> { where(record_type: 'hierarchy') }

  def self.possible_parents(vocab)
    vocab ? (all-vocab.self_and_descendants) : all
  end

  def name_for_select
    '- ' * depth + prefered_term.name
  end

  def self.arrange_as_tree(options={}, hash=nil)
    hash ||= hash_tree(options)

    arr = []
    hash.each do |node, children|
      arr << node
      arr += arrange_as_tree(options, children) unless children.nil?
    end
    arr
  end

  def prefered_term
  	terms.where(prefered: true).first || terms.first
  end

  def prefered_note
    comments.where(prefered: true).first || comments.first
  end

  def other_notes
    comments.where(prefered: false)
  end

end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  layout 'page'
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_vocabulary, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vocabularies = Vocabulary.all
    respond_with(@vocabularies)
  end

  def show
    @artefacts = @vocabulary.self_and_descendants.map{ |v| v.artefacts }.flatten.sort_by { |i| [i ? 0 : 1, i] }
    respond_with(@vocabulary)
  end

  def new
    @vocabulary = Vocabulary.new(parent_id: params[:parent_id])
    @vocabulary.terms.build
    respond_with(@vocabulary)
  end

  def edit
  end

  def create
    @vocabulary = Vocabulary.new(vocabulary_params.merge(creator: current_user, updater: current_user))
    flash[:notice] = 'Term was successfully created.' if @vocabulary.save
    respond_with(@vocabulary)
  end

  def update
    flash[:notice] = 'Term was successfully updated.' if @vocabulary.update(vocabulary_params.merge(updater: current_user))
    respond_with(@vocabulary)
  end

  def destroy
    @vocabulary.destroy
    respond_with(@vocabulary)
  end

  private
    def set_vocabulary
      @vocabulary = Vocabulary.find(params[:id])
    end

    def vocabulary_params
      params.require(:vocabulary).permit(:record_type, :parent_id, terms_attributes: [:id, :prefered, :name, :language, :_destroy],
        comments_attributes: [:id, :prefered, :content, :language, :_destroy])
    end
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/vocabularies/_form.html.erb
<%= simple_form_for @vocabulary, html: { class: 'form-horizontal' },
      wrapper: :horizontal_form,
      wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
      } do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.error_notification %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="general-fields" style="margin-top:20px;">
        <%= f.input :record_type, collection: ["hierarchy", "concept"] %>
        <%= f.input :parent_id, collection: Vocabulary.possible_parents(@vocabulary), label_method: :name_for_select, value_method: :id, include_blank: true %>
      </div>
      <%= content_tag :div, id: 'terms' do %>
        <%= f.simple_fields_for :terms do |ident| %>
          <%= render 'term_fields', f: ident %>
        <% end %>
        <div class="add-fields">
          <%= link_to_add_association 'add language', f, :terms, class: 'btn btn-default btn-xs' %>
        </div>
      <% end %>
      <%= f.button :submit, class: 'btn btn-primary', style: 'margin-top:20px;' %>
    </div>
    <div class="col-sm-6">
      <h4>Notes</h4>
      <%= content_tag :div, id: 'comments' do %>
        <%= f.simple_fields_for :comments do |ident| %>
          <%= render 'comment_fields', f: ident %>
        <% end %>
        <div class="add-fields">
          <%= link_to_add_association 'add note', f, :comments, class: 'btn btn-default btn-xs' %>
        </div>
      <% end %>

    </div>
  </div>
<% end %>

app/views/vocabularies/_term_fields.html.erb
<%= content_tag :div, class: 'nested-fields' do %>
  <%= f.input :name, label: "Term name #{content_tag :span, link_to_remove_association("remove", f), class: 'remove-link'}".html_safe %>
  <%= f.input :language, collection: ["de-DE", "en-US", "fr-FR"] %>
  <div class="col-sm-offset-3" style='padding-left: 8px'>
  	<div class="checkbox">
  	  <%= f.input_field :prefered, as: :boolean, inline_label: 'Prefered term'  %>
	</div>
  </div>
<% end %>

app/views/vocabularies/edit.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), vocabularies_path, title: 'back' %> 
    Editing vocabulary term
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Discard changes/back', :back, class: 'btn btn-default' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<%= render 'form' %>

app/views/vocabularies/index.html.erb
<% content_for :title_bar do %>
  <h1>
    Vocabularies
    <%= link_to 'Add vocabulary', new_vocabulary_path, class: 'btn btn-default pull-right' if user_signed_in? %>
  </h1>
<% end %>

<h2>
  <i class="fa fa-bars" style="color:#428bca;"></i>
  Terms
</h2>
<div class="row">
  <div class="col-sm-4">
    <ul class="list-unstyled">
      <% for term in @vocabularies.arrange_as_tree do %>
        <%= content_tag :li do %>
          <%= link_to term.prefered_term.name, term, style: "#{'margin-left:'+(term.depth*20).to_s+'px'}; #{'font-weight:bold;margin-top:10px;' if term.root?}" %> 
          <%= content_tag :span, term.record_type, class: 'text-muted pull-right', style: 'font-size:85%;' %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/vocabularies/new.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), vocabularies_path, title: 'back' %>
    New vocabulary term
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Discard changes/back', :back, class: 'btn btn-default' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<%= render 'form' %>

app/views/vocabularies/show.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), vocabularies_path, title: 'back' %> <%= @vocabulary.prefered_term.name %>
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Edit term', edit_vocabulary_path(@vocabulary), class: 'btn btn-default' %>
      <%= link_to 'Add sub term', new_vocabulary_path(parent_id: @vocabulary), class: 'btn btn-default' %>
      <%= link_to 'Destroy', @vocabulary, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-danger' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<div class="row">
  <div class="col-sm-5">
    <p>
      <strong>ID: <%= @vocabulary.id %></strong>
      <span class="pull-right"><strong>Record type: </strong><%= @vocabulary.record_type %></span>
    </p>
    <div id="term">
      <p>
        <i class="fa fa-bars" style="color:#428bca;"></i>
        <strong><%= @vocabulary.prefered_term.name %></strong> (<%= @vocabulary.prefered_term.language %>)
      </p>
    </div>
    <div id="note">
      <p>
        <strong>Note: </strong>
        <%= @vocabulary.prefered_note.try(:content) || content_tag(:em, 'undefined') %>
      </p>
    </div>
    <div id="terms">
      <strong>Terms:</strong>
      <ul class="list-unstyled">
        <% for term in @vocabulary.terms.order(id: :asc) %>
          <%= content_tag :li, style: "padding-left:20px;#{'font-weight:bold;' if term == @vocabulary.prefered_term}" do %>
            <%= term.name %> (<%= term.language %>)
          <% end %>
        <% end %>
      </ul>
    </div>
    <div id="hierarchy">
      <strong>Hierarchical Position:</strong>
      <ul class="list-unstyled">
        <% for term in @vocabulary.root.self_and_descendants.arrange_as_tree do %>
          <%= content_tag :li, style: "#{'font-weight:bold;' if term == @vocabulary}" do %>
            <%= link_to term.prefered_term.name, term, style: 'margin-left:'+(term.depth*15).to_s+'px' %>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div id="notes">
      <strong>Additional Notes:</strong>
      <% for note in @vocabulary.other_notes %>
        <p><%= note.content %> (<%= note.language %>)</p>
      <% end %>
    </div>

    <% if user_signed_in? %>
    <br>
      <p>
        <strong>Creator:</strong>
        <%= @vocabulary.creator.try(:email) %>
      <br>
        <strong>Updater:</strong>
        <%= @vocabulary.updater.try(:email) %>
      </p>
    <% end %>
  </div>

  <div class="col-sm-6 col-sm-offset-1">
    <h4>Artefacts with/for <%= @vocabulary.prefered_term.name %></h4>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>Identificators</td>
          <td>Info</td>
        </tr>
      </thead>
      <tbody>
        <%= render @artefacts %>
      </tbody>
    </table>
  </div>
</div>