config/routes.rb
Rails.application.routes.draw do
  resources :vocabularies

  resources :excavations

  resources :artefacts

  devise_for :users
  
  get 'home/index'

  root 'home#index'

end

app/models/artefact.rb
class Artefact < ActiveRecord::Base
  dragonfly_accessor :image
  dragonfly_accessor :drawing

  has_many :artefact_identificators, dependent: :destroy
  has_many :excavations, through: :artefact_identificators
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :restorations, dependent: :destroy
  has_many :dispositions, dependent: :destroy
  has_many :specifications, as: :specifyable, dependent: :destroy
  has_many :terms, class_name: 'Vocabulary', through: :specifications, source: :vocabulary

  belongs_to :creator, class_name: 'User'
  belongs_to :updater, class_name: 'User'

  accepts_nested_attributes_for :artefact_identificators, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :restorations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :dispositions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :specifications, reject_if: :all_blank, allow_destroy: true

  default_scope {order(dez: :asc)}

  def name
    if dez
      "DeZ #{dez}#{dez_index}"
    elsif artefact_identificators.any?
      'undefined'
    end 
  end

  # filter config
  ransacker :sdez do #convert dez to string
    Arel.sql("to_char(dez, '9999999')")
  end

  ransacker :fdez do |parent|
    Arel::Nodes::InfixOperation.new('||',
      parent.table[:dez], parent.table[:dez_index])
  end
end

app/controllers/artefacts_controller.rb
class ArtefactsController < ApplicationController
  layout 'page'
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_artefact, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @q = Artefact.search(params[:q])
    @artefacts = @q.result(distinct: true).paginate(page: params[:page], per_page: 30)
    respond_with(@artefacts)
  end

  def show
    respond_with(@artefact)
  end

  def new
    @artefact = Artefact.new
    @artefact.artefact_identificators.build
    respond_with(@artefact)
  end

  def edit
  end

  def create
    @artefact = Artefact.new(artefact_params.merge(creator: current_user, updater: current_user))
    flash[:notice] = 'Artefact was successfully created.' if @artefact.save
    respond_with(@artefact)
  end

  def update
    if @artefact.update(artefact_params.merge(updater: current_user))
      flash[:notice] = 'Artefact was successfully updated.'
      respond_with(@artefact)
    else 
      raise 'error while updating'
    end
  end

  def destroy
    @artefact.destroy
    respond_with(@artefact)
  end

  private
    def set_artefact
      @artefact = Artefact.find(params[:id])
    end

    def artefact_params
      params.require(:artefact).permit(:image, :drawing, :publications, :dimensions, :dimensions_type, :weight, :dez, :dez_index, 
        :in_exhibition, :state_of_preservation, artefact_identificators_attributes: [:id, :artefact_id, :name, :fjno, :excavation_id, :_destroy, comments_attributes: [:id, :content, :language, :_destroy]], 
        comments_attributes: [:id, :content, :language, :_destroy], restorations_attributes: [:id, :date_of_action, :_destroy, comments_attributes: [:id, :content, :language, :_destroy]],
        dispositions_attributes: [:id, :receipt_date, :location, :_destroy, comments_attributes: [:id, :content, :language, :_destroy]], specifications_attributes: [:id, :vocabulary_id, :_destroy])
    end
end

app/helpers/artefacts_helper.rb
module ArtefactsHelper
end

app/views/artefacts/_artefact.html.erb
<tr>
  <td>
    <p><%= link_to artefact.name, artefact %></p>
    <%= content_tag :p do %>
      <small>
        <%= artefact.artefact_identificators.map{|ai| "#{link_to(ai.excavation_name, ai.excavation)} #{ai.name}"}.join(', ').html_safe %>
      </small>
    <% end if artefact.artefact_identificators.any? %>
  </td>
  <td class="col-sm-9">
    <%= link_to content_tag(:i, '', class: 'fa fa-chevron-right fa-1x'), artefact, class: 'pull-right', title: 'show artefact' %>
    <p><%= artefact.terms.map{|t| link_to(t.prefered_term.name, t)}.join(', ').html_safe %></p>
    <p style="font-size: 80%"><%= truncate(artefact.comments.last.content) if artefact.comments.any? %></p>
  </td>
</tr>

app/views/artefacts/_artefact_identificator_fields.html.erb
<%= content_tag :div, class: 'nested-fields' do %>
  <%= f.association :excavation, label: "Excavation #{content_tag :span, link_to_remove_association("remove", f), class: 'remove-link'}".html_safe %>
  <%= f.input :name, label: 'Original identificator', hint: 'Please omit any excavation shortcuts here.' %>
  <%= f.input :fjno, label: 'Fundjournal', hint: 'If present.' %>
  <%= content_tag :div, id: 'comments' do %>
    <%= f.simple_fields_for :comments do |ident| %>
      <%= render 'comment_fields', f: ident %>
    <% end %>
    <div class="add-fields">
      <%= link_to_add_association 'Add note', f, :comments, class: 'col-sm-offset-3 btn btn-default btn-xs' %>
    </div>
  <% end %>
<% end %>

app/views/artefacts/_detail.js.erb
some text

app/views/artefacts/_disposition_fields.html.erb
<%= content_tag :div, class: 'nested-fields' do %>
  <%= f.input :receipt_date, as: :date, start_year: Date.today.year - 100, label: "Receipt date #{content_tag :span, link_to_remove_association("remove", f), class: 'remove-link'}".html_safe %>
  <%= f.input :location, label: "Location" %>
  <%= content_tag :div, id: 'comments' do %>
    <%= f.simple_fields_for :comments do |ident| %>
      <%= render 'comment_fields', f: ident %>
    <% end %>
    <div class="add-fields">
      <%= link_to_add_association 'Add note', f, :comments, class: 'col-sm-offset-3 btn btn-default btn-xs' %>
    </div>
  <% end %>
<% end %>

app/views/artefacts/_form.html.erb
<%= simple_form_for @artefact, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>

  <div class="row">
    <div class="col-sm-12">   
      <%= f.error_notification %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <h4>General info</h4>
      <div class="general-fields">
        <%= f.input :dez %>
        <%= f.input :dez_index %>
        <%= f.input :in_exhibition %>
        <%= f.input :state_of_preservation %>
        <%= f.input :image, as: :file %>
        <%= f.input :drawing, as: :file %>
  
        <%= f.input :dimensions %>
        <%= f.input :dimensions_type %>
        <%= f.input :weight %>

        <%= f.input :publications, as: :text %>
      </div>
      <%= content_tag :div, id: 'comments' do %>
        <h4>Notes</h4>
        <%= f.simple_fields_for :comments do |ident| %>
          <%= render 'comment_fields', f: ident %>
        <% end %>
        <div class="add-fields">
          <%= link_to_add_association 'Add note', f, :comments, class: 'btn btn-default btn-xs' %>
        </div>
      <% end %>

      <%= f.button :submit, class: 'btn btn-primary', style: 'margin-top:20px;' %>
    </div>
    <div class="col-sm-6">
      <%= content_tag :div, id: 'artefact_identificators' do %>
        <h4>Identificators</h4>
        <%= f.simple_fields_for :artefact_identificators do |ident| %>
          <%= render 'artefact_identificator_fields', f: ident %>
        <% end %>
        <div class="add-fields">
          <%= link_to_add_association 'Add identificator', f, :artefact_identificators, class: 'btn btn-default btn-xs' %>
        </div>
      <% end %>
      <hr>
      <%= content_tag :div, id: 'specifications' do %>
        <h4>Classification/Material/Technique</h4>
        <%= f.simple_fields_for :specifications do |ident| %>
          <%= render partial: 'specification_fields', locals: {f: ident, hierarchy: Vocabulary.roots } %>
        <% end %>
        <div class="add-fields" style="display:inline;">
          <% for hierarchy in Vocabulary.roots do %>
            <%= link_to_add_association "Add #{hierarchy.prefered_term.name}", f, :specifications, :render_options => {locals: { hierarchy: hierarchy }}, class: 'btn btn-default btn-xs' %>
          <% end %>
        </div>
      <% end %>
      <hr>
      <%= content_tag :div, id: 'dispositions' do %>
        <h4>Disposition</h4>
        <%= f.simple_fields_for :dispositions do |ident| %>
          <%= render 'disposition_fields', f: ident %>
        <% end %>
        <div class="add-fields">
          <%= link_to_add_association 'Add disposition', f, :dispositions, class: 'btn btn-default btn-xs' %>
        </div>
      <% end %>
      <hr>
      <%= content_tag :div, id: 'restorations' do %>
        <h4>Restorations</h4>
        <%= f.simple_fields_for :restorations do |ident| %>
          <%= render 'restoration_fields', f: ident %>
        <% end %>
        <div class="add-fields">
          <%= link_to_add_association 'Add restoration', f, :restorations, class: 'btn btn-default btn-xs' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      
    </div>
  </div>
<% end %>

app/views/artefacts/_restoration_fields.html.erb
<%= content_tag :div, class: 'nested-fields' do %>
  <%= f.input :date_of_action, as: :date, start_year: Date.today.year - 100, label: "Date of action #{content_tag :span, link_to_remove_association("remove", f), class: 'remove-link'}".html_safe %>
  <%= content_tag :div, id: 'comments' do %>
    <%= f.simple_fields_for :comments do |ident| %>
      <%= render 'comment_fields', f: ident %>
    <% end %>
    <div class="add-fields">
      <%= link_to_add_association 'Add note', f, :comments, class: 'col-sm-offset-3 btn btn-default btn-xs' %>
    </div>
  <% end %>
<% end %>

app/views/artefacts/_specification_fields.html.erb
<%= content_tag :div, class: 'nested-fields' do %>
  <% unless f.object.new_record? %>
  	<%= f.object.vocabulary.self_and_ancestors.reverse.map{|t| link_to t.root? ? content_tag(:span, t.prefered_term.name, style: 'font-weight: bold') : t.prefered_term.name, t }.join(' > ').html_safe %>
  	<%= content_tag :span, link_to_remove_association("remove", f), class: 'remove-link' %>
  <% end %>
  <% collection = hierarchy.descendants %>
  <%= f.association :vocabulary, label: "#{hierarchy.prefered_term.name} term #{content_tag :span, link_to_remove_association("remove", f), class: 'remove-link'}".html_safe, collection: collection, label_method: :name_for_select, value_method: :id, include_blank: true if f.object.new_record? %>

<% end %>



app/views/artefacts/edit.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), artefacts_path, title: 'back' %> Editing artefact
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Discard changes/back', :back, class: 'btn btn-default' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<%= render 'form' %>

app/views/artefacts/index.html.erb
<% content_for :title_bar do %>
  <h1>
    Artefacts
    <%= link_to 'Add Artefact', new_artefact_path, class: 'btn btn-default pull-right' if user_signed_in? %>
  </h1>
<% end %>
<div class="row">
  <div class="col-sm-8">
    <%= will_paginate(@artefacts, previous_label: '&laquo;', next_label: '&raquo;', renderer: WillPaginate::ActionView::BootstrapLinkRenderer) %>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>Identificators</td>
          <td>Info</td>
        </tr>
      </thead>
      <tbody>
        <% @artefacts.order(dez: :asc).each do |artefact| %>
          <tr>
            <td>
              <p>
                <small>
                  <%= content_tag :i, '', class: "fa fa-university pull-right text-muted", title: 'exhibited' if artefact.in_exhibition %>
                  <%= content_tag :i, '', class: "fa fa-file-image-o pull-right text-muted", title: 'with photo' if artefact.image %>
                </small>
                <%= link_to artefact.name, artefact, style: 'font-weight: bold' %>
              </p>
              <%= content_tag :p do %>
                <small>
                  <%= artefact.artefact_identificators.map{|ai| "#{link_to(ai.excavation_name, ai.excavation)} #{ai.name}"}.join(', ').html_safe %>
                </small>
              <% end if artefact.artefact_identificators.any? %>
            </td>
            <td class="col-sm-9">
              <%= link_to content_tag(:i, '', class: 'fa fa-chevron-right fa-1x'), artefact, class: 'pull-right', title: 'show artefact' %>
              <ul class="list-unstyled">
                <% for term in artefact.terms.order(parent_id: :asc) do %>
                  <li><%= term.self_and_ancestors.reverse.map{|t| link_to t.root? ? content_tag(:span, t.prefered_term.name, style: 'font-weight: normal') : t.prefered_term.name, t }.join(' > ').html_safe %></li>
                <% end %>
              </ul>
              <p style="font-size: 80%"><%= truncate(artefact.comments.last.content) if artefact.comments.any? %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-3 col-sm-offset-1">
    <%= content_tag :div, class: "well" do %>
      <h4>Filters</h4>
      <%= search_form_for @q do |f| %>
        <%= f.input :fdez_cont, required: false, label: 'DeZ contains', placeholder: 'No + index' %>
        <%= f.input :excavations_name_or_excavations_shortcut_cont, required: false, label: 'Excavation', placeholder: 'name or shortcut' %>
        <%= f.input :artefact_identificators_name_cont, required: false, label: 'Excavations id', placeholder: 'name' %>

        <div style="border:1px solid red;padding:5px;">
        <% Vocabulary.roots.each do |root| %>
          <p><strong><%= root.prefered_term.name %></strong><br>
            <% root.descendants.each do |term| %>
              <%= check_box_tag('q[terms_id_in][]', term.id) %>
              <%= term.prefered_term.name %>
            <% end %>
          </p>
        <% end %>
        </div>

        

        <div class="submit" style="margin-top:10px;">
          <%= f.submit 'Filter', class: 'btn btn-default' %><%= link_to 'Reset', artefacts_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/artefacts/new.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), artefacts_path, title: 'back' %> New artefact
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Discard changes/back', :back, class: 'btn btn-default' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<%= render 'form' %>

app/views/artefacts/show.html.erb
<% content_for :title_bar do %>
  <h1>
    <%= link_to content_tag(:i, '', class: "fa fa-chevron-left"), artefacts_path, title: 'back' %> <%= @artefact.name %>
    <%= content_tag :div, class: 'pull-right' do %>
      <%= link_to 'Edit Artefact', edit_artefact_path(@artefact), class: 'btn btn-default' %>
      <%= link_to 'Destroy', @artefact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-danger' %>
    <% end if user_signed_in? %>
  </h1>
<% end %>

<div class="row">

  <div class="col-sm-5 artefact-desc">
    <%= content_tag :ul, class: 'list-unstyled' do %>
      <h4>Excavation ids</h4>
      <% @artefact.artefact_identificators.each do |ai| %>
        <li><%= link_to(ai.excavation_name, ai.excavation) %> <%= ai.name %> <%= content_tag :span, "(Fj.Nr: #{ai.fjno})" if ai.fjno.present? %> </li>
      <% end %>
    <% end if @artefact.artefact_identificators.any? %>
    
    <h4>Artefact details</h4>
    <ul class="list-unstyled">
    <% for term in @artefact.terms.order(parent_id: :asc) do %>
      <li><%= term.self_and_ancestors.reverse.map{|t| link_to t.root? ? content_tag(:span, t.prefered_term.name, style: 'font-weight: bold') : t.prefered_term.name, t }.join(' > ').html_safe %></li>
    <% end %>
    </ul>
    <p>
      <strong>Dimensions:</strong>
      <%= @artefact.dimensions %><br>
      <!-- <strong>Dimensions type:</strong>
      <%= @artefact.dimensions_type %><br> -->
      <strong>Weight:</strong>
      <%= @artefact.weight %>
    </p>
    
    <h4>
      <small><%= content_tag :i, '', class: "fa #{@artefact.in_exhibition ? 'fa-university' : 'fa-archive'}", title: (@artefact.in_exhibition ? 'exhibited' : 'archived') %></small>
      Disposition
    </h4>
    <% @artefact.dispositions.order(receipt_date: :desc).each do |disp| %>
      <p>
        <%= disp.location %> 
        <small>(<%= disp.receipt_date.to_date.to_s(:long) %>)</small>
        <ul class="text-muted list-unstyled">
          <% disp.comments.order(created_at: :desc).each do |c| %>
            <li><%= c.content %> (<%= c.language %>)</li>
          <% end %>
        </ul>
      </p>
    <% end %>
    
    <h4>
      <small><%= content_tag :i, '', class: "fa fa-medkit", title: 'restored' %></small>
      Restorations
    </h4>
    <% @artefact.restorations.order(date_of_action: :desc).each do |rest| %>
      <p>
        <%= rest.date_of_action.to_date.to_s(:long) %>
        <ul class="text-muted list-unstyled">
          <% rest.comments.order(created_at: :desc).each do |c| %>
            <li><%= c.content %> (<%= c.language %>)</li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <h4>
      <small><%= content_tag :i, '', class: "fa fa-comments", title: 'notes' %></small>
      Notes
    </h4>
    <p style=""><%= truncate(@artefact.comments.last.content) if @artefact.comments.any? %></p>

    <div id="publication">
      <h4>Publications</h4>
      <%= @artefact.publications %>
    </div>

    <% if user_signed_in? %>
      <br/><br/>
      <p>
        <strong>Creator:</strong>
        <%= @artefact.creator.try(:email) %>
      <br>
        <strong>Updater:</strong>
        <%= @artefact.updater.try(:email) %>
      </p>
    <% end %>
  </div>
  <div class="col-sm-6 col-sm-offset-1">
    <div id="image">
      <%= image_tag @artefact.image.thumb('600x900').url, class: 'img-responsive', id: "artefact-image-#{@artefact.id}-#{@artefact.created_at.to_s.parameterize}" if @artefact.image_stored? %>
    </div>
    <br/>
    <div id="drawing">
      <%= image_tag @artefact.drawing.thumb('600x900').url, class: 'img-responsive', id: "artefact-drawing-#{@artefact.id}-#{@artefact.created_at.to_s.parameterize}" if @artefact.drawing_stored? %>
    </div>

  </div>
</div>